### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gitrichhub** [rebel7580/MQTT-Plug-in-For-HomeVisionXL#1]
Would it be possible to add IR Commands to the Object Type List for Internal Objects?  This would be helpful to send IR commands to HV from external MQTT request.  Thanks again for the awesome plugin!!

**Comment by rebel7580** [comment]
IR objects weren't included as they had no "state", and couldn't be "controlled" from that point of view.

However, with the latest version of the plug-in, you can now do IR commands via triggers. See the MQTT help for details.

Short version:
- Enable the latest versions of the MQTT and actions plug-ins if you haven't done so.
- Create an EXTERNAL object with an appropriate topic/name. Depending on how you want to configure your MQTT message to work, you may need to be explicit with a full topic.  A standard topic - one defined as `<topic>` - will subscribe to `stat/topic/POWER`, which may not be what you want to send to control IR. You may be better off setting your topic explicitly to something like `cmnd/HVIR/irsend`.  Then  you would put the IR number into the payload.
- Assuming the above, select "Trigger" and "Custom".
- Add the following to the Trigger field:
   ` action: ir transmit %M 1;`
- An MQTT command like this:
`cmnd/HVIR/irsend 5`
would cause the above action trigger to fire.
- If you need to repeat a particular IR signal, leave off the "1" (for send once), and make sure your payload always has 
`IR# #repeats`
even if you only need "once" most of the time.

Please send future requests, etc. via the homevision users group at homevision-users@googlegroups.com

**Comment by rebel7580** [comment]
@gitrichhub  Let me know if this solves your need or not, or if you need more support to get this to work for you.

**Comment by gitrichhub** [comment]
Sorry, Ron this went to my spam box and I missed your note.  I think this will work.  I should have dug deeper before I called you in.  I’ve lost my access to the group.  Thanks for your help.  Again!  😁

John

**Comment by rebel7580** [comment]
John -

When I saw your original issue, I thought "gitrichhub" might be you, and I
noticed that there wasn't an entry in the new google group for you, at
least not one I recognized.

Did you try to sign up for the new group? In any case, I can add you to it
if you give me an email address you would like to use with it (gmail one is
best if you have one, but any should work.)

Ron

**Comment by rebel7580** [comment]
Implemented in version 1.87
